### ISSUE TITLE
Drop Vite and embrace htmx 2.0.0?

### ISSUE THREAD

**Issue by shroominic** [pydantic/FastUI#335] opened 2024-06-21 21:11 UTC
I think now with htmx 2.0.0 we can migrate to just having a python worker outputting html instead of json.

**Comment by samuelcolvin** [comment] 2024-06-22 07:03
Duplicate of #48.

But the hard bit isn't htmx, it's the template rendering in python.

**Closed by samuelcolvin** 2024-06-22 07:03 UTC

**Comment by hasansezertasan** [comment] 2024-06-22 10:30
> I think now with htmx 2.0.0 we can migrate to just having a python worker outputting html instead of json.


Check out Ludic.
