### ISSUE TITLE
Use different path for UI API

### ISSUE THREAD

**Issue by varadinov** [pydantic/FastUI#152] opened 2024-01-15 16:12 UTC
Hi,
I'm trying to create a FastAPI project that contains both REST API and UI. I would like the API to be served on /api and respectively the UI to be served on /ui and the API for the UI to be served in /ui/api. This way the application will be able to provide API for external services.
Currently I don't see an option to set a path for the API for the UI in prebuilt_html.

P.S. Is there a discord server or other option for community communication for FastUI?

**Comment by hasansezertasan** [comment] 2024-01-16 00:41
Related to #134

**Comment by samuelcolvin** [comment] 2024-02-09 06:58
I agree duplicate of #134.

There's no discord server, I find they're a time sink for the maintainer.

**Closed by samuelcolvin** 2024-02-09 06:58 UTC
