### ISSUE TITLE
Returning a `201` raises an error in the ui

### ISSUE THREAD

**Issue by tim-habitat** [pydantic/FastUI#245] opened 2024-03-12 15:51 UTC
While generating a sign-up flow, i think it is common to return a `201` to signal user created. However, the app catches that as an exception and raised an alert toast.
Example:
```python
@router.post(
        "/register",
        response_model=user_schema,
        status_code=status.HTTP_201_CREATED,
        name="register:register",
    )    
async def register(
):
...
```
![image](https://github.com/pydantic/FastUI/assets/86600518/0a3e195b-c2f5-4604-ba54-5ed56add3b27)

**Comment by samuelcolvin** [comment] 2024-03-12 21:46
Duplicate of #225.

**Closed** 2024-03-20 10:26 UTC
