### ISSUE TITLE
pydantic.errors.PydanticUserError: `Page` is not fully defined; you should define `AnyComponent`, then call `Page.model_rebuild()`.

### ISSUE THREAD

**Issue by x4zx** [pydantic/FastUI#371] opened 2024-12-03 23:57 UTC
I tried to run your same code from the example and got an error:
```
pydantic.errors.PydanticUserError: `Page` is not fully defined; you should define `AnyComponent`, then call `Page.model_rebuild()`.
```

Maximum uncomfortable communication with the community. To contact and solve a problem you need to go to a channel on Slack, and to go there you need mail `...@pydantic.dev` which is not clear where to get. 

```py
from datetime import date

from fastapi import FastAPI, HTTPException
from fastapi.responses import HTMLResponse
from fastui import FastUI, AnyComponent, prebuilt_html, components as c
from fastui.components.display import DisplayMode, DisplayLookup
from fastui.events import GoToEvent, BackEvent
from pydantic import BaseModel, Field

app = FastAPI()


class User(BaseModel):
    id: int
    name: str
    dob: date = Field(title='Date of Birth')


# define some users
users = [
    User(id=1, name='John', dob=date(1990, 1, 1)),
    User(id=2, name='Jack', dob=date(1991, 1, 1)),
    User(id=3, name='Jill', dob=date(1992, 1, 1)),
    User(id=4, name='Jane', dob=date(1993, 1, 1)),
]


@app.get("/api/", response_model=FastUI, response_model_exclude_none=True)
def users_table() -> list[AnyComponent]:
    """
    Show a table of four users, `/api` is the endpoint the frontend will connect to
    when a user visits `/` to fetch components to render.
    """
    return [
        c.Page(  # Page provides a basic container for components
            components=[
                c.Heading(text='Users', level=2),  # renders `<h2>Users</h2>`
                c.Table(
                    data=users,
                    # define two columns for the table
                    columns=[
                        # the first is the users, name rendered as a link to their profile
                        DisplayLookup(field='name', on_click=GoToEvent(url='/user/{id}/')),
                        # the second is the date of birth, rendered as a date
                        DisplayLookup(field='dob', mode=DisplayMode.date),
                    ],
                ),
            ]
        ),
    ]


@app.get("/api/user/{user_id}/", response_model=FastUI, response_model_exclude_none=True)
def user_profile(user_id: int) -> list[AnyComponent]:
    """
    User profile page, the frontend will fetch this when the user visits `/user/{id}/`.
    """
    try:
        user = next(u for u in users if u.id == user_id)
    except StopIteration:
        raise HTTPException(status_code=404, detail="User not found")
    return [
        c.Page(
            components=[
                c.Heading(text=user.name, level=2),
                c.Link(components=[c.Text(text='Back')], on_click=BackEvent()),
                c.Details(data=user),
            ]
        ),
    ]


@app.get('/{path:path}')
async def html_landing() -> HTMLResponse:
    """Simple HTML page which serves the React app, comes last as it matches all paths."""
    return HTMLResponse(prebuilt_html(title='FastUI Demo'))
```

**Comment by Kilo59** [comment] 2024-12-04 14:36
@hramezani I got this same issue on 2.10.
When I pinned to an earlier version the issue went away.

**Comment by hramezani** [comment] 2024-12-04 14:40
let's mark it as a duplicate of https://github.com/pydantic/FastUI/issues/369 and close

**Closed by hramezani** 2024-12-04 14:40 UTC
