### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by stikkireddy** [pydantic/FastUI#165] opened 2024-01-25 17:36 UTC
I am running my fastapi behind a proxy. The issue I am running into:
assume my path is `https://example.com/proxy/8989/`

1. the root path is invoked
2. the HTMLResponse(prebuilt_html(title='FastUI Demo')) is sent
3. the following content is run

```
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>FastUI Demo</title>
    <script type="module" crossorigin src="https://cdn.jsdelivr.net/npm/@pydantic/fastui-prebuilt@0.0.15/dist/assets/index.js"></script>
    <link rel="stylesheet" crossorigin href="https://cdn.jsdelivr.net/npm/@pydantic/fastui-prebuilt@0.0.15/dist/assets/index.css">
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>
```

4. The index.js is installed
5. Then it makes an fetch call with the react js being loaded to `https://example.com/api/proxy/8989/` instead of `https://example.com/proxy/8989/api/`

Is this expected? Any plans on fixing it?

**Comment by samuelcolvin** [comment] 2024-02-09 07:04
I think this is a duplicate of #134, LMK if that's not the case and we can reopen.

**Closed by samuelcolvin** 2024-02-09 07:04 UTC
