### ISSUE TITLE
`FastAPI` dependency

### ISSUE THREAD

**Issue by AliRn76** [pydantic/FastUI#131] opened 2023-12-27 23:35 UTC
In the `Readme.md` we have this:
> While it works well with [FastAPI](https://fastapi.tiangolo.com/) it doesn't depend on FastAPI, and most of it could be used with any python web framework.

But in RL we can't run the project when `fastapi` is not installed:
![Screenshot from 2023-12-28 02-15-39](https://github.com/pydantic/FastUI/assets/40032682/dee4183a-a904-4618-8e96-0dff353dfdf9)

I'm working on a built-in admin-panel for the [Panther](https://github.com/alirn76/panther), and it would be awesome if we could fix this requirement,
and ofc I'm ready to help you with this issue, but I'm not sure what scenario you have in your mind.

- We can have our own 
  1. `UploadFile` model instead of `ds.UploadFile`
  2. `Depends` model instead of `fastapi.params.Depends`
  3. `HTTPException` instead of `fastapi.HTTPException`
  4. `FormData` instead of `ds.FormData`
  5. And in the `fastui.forms.fastui_form()` we can get the final form data instead of request, so we can use this function with any type of form in other frameworks

- Or we can just change the location of the imports so these things won't load on the init

Btw, I think this is a useful project and I would be happy if I could help with it ✋🏽

**Comment by samuelcolvin** [comment] 2023-12-27 23:46
Duplicate of #85.

Please try to do some research before creating issues.

**Closed by samuelcolvin** 2023-12-27 23:46 UTC

**Comment by AliRn76** [comment] 2023-12-28 00:22
Sorry, that was my bad, but can I ask, do you have any plan to remove the fastapi requirement in the future or at least make it required if user wants to use the form stuff? because now we have to install it in any case.
